-- MySQL Script generated by MySQL Workbench
-- Thu Dec  5 15:02:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema a-king-s-ransom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema a-king-s-ransom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `a-king-s-ransom` DEFAULT CHARACTER SET cp1251 ;
USE `a-king-s-ransom` ;

-- -----------------------------------------------------
-- Table `a-king-s-ransom`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a-king-s-ransom`.`customers` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `number_of_orders` INT(11) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CUSTOMER_NAME` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `a-king-s-ransom`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a-king-s-ransom`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `secret_answer` VARCHAR(255) NULL DEFAULT 'q',
  `secret_question` VARCHAR(255) NULL DEFAULT 'q',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `a-king-s-ransom`.`customer_representative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a-king-s-ransom`.`customer_representative` (
  `customer_representative_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`customer_representative_ID`),
  UNIQUE INDEX `customer_reprecentative` (`customer_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `user_id_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `custoner_id_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `a-king-s-ransom`.`customers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `user_id_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `a-king-s-ransom`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 230
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `a-king-s-ransom`.`manager_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a-king-s-ransom`.`manager_data` (
  `manager_id` INT(10) UNSIGNED NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`manager_id`),
  CONSTRAINT `manager_data_id_user_id`
    FOREIGN KEY (`manager_id`)
    REFERENCES `a-king-s-ransom`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `a-king-s-ransom`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a-king-s-ransom`.`orders` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_ID` INT(11) UNSIGNED NOT NULL,
  `order_name` VARCHAR(255) NOT NULL,
  `date_of_receiving` DATE NOT NULL,
  `date_of_completion` DATE NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  `payment` VARCHAR(45) NOT NULL,
  `manager_ID` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `custoner_id_idx` (`customer_ID` ASC) VISIBLE,
  INDEX `manager_id_idx` (`manager_ID` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `a-king-s-ransom`.`customers` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `manager_id`
    FOREIGN KEY (`manager_ID`)
    REFERENCES `a-king-s-ransom`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `a-king-s-ransom`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a-king-s-ransom`.`products` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT(10) UNSIGNED NULL DEFAULT NULL,
  `unit_price` DECIMAL(10,4) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 153
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `a-king-s-ransom`.`product_in_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a-king-s-ransom`.`product_in_orders` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_ID` INT(10) UNSIGNED NOT NULL,
  `order_ID` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `product_ID_in_product_in_orders_idx` (`product_ID` ASC) VISIBLE,
  INDEX `order_ID_In_product_in_order_idx` (`order_ID` ASC) VISIBLE,
  CONSTRAINT `order_ID_In_product_in_order`
    FOREIGN KEY (`order_ID`)
    REFERENCES `a-king-s-ransom`.`orders` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `product_ID_in_product_in_orders`
    FOREIGN KEY (`product_ID`)
    REFERENCES `a-king-s-ransom`.`products` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 73
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `a-king-s-ransom`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a-king-s-ransom`.`providers` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `rating` INT(10) UNSIGNED NULL DEFAULT '0',
  `location` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `a-king-s-ransom`.`product_in_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a-king-s-ransom`.`product_in_stock` (
  `product_in_stock_ID` INT(10) UNSIGNED NOT NULL,
  `provider_ID` INT(10) UNSIGNED NOT NULL,
  `receipt_date` DATE NOT NULL,
  PRIMARY KEY (`product_in_stock_ID`),
  INDEX `providers_ID_idx` (`provider_ID` ASC) VISIBLE,
  INDEX `providers_ID_providers_idx` (`provider_ID` ASC) VISIBLE,
  CONSTRAINT `id_product_in_stock_id_product`
    FOREIGN KEY (`product_in_stock_ID`)
    REFERENCES `a-king-s-ransom`.`products` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `providers_ID_in_stock`
    FOREIGN KEY (`provider_ID`)
    REFERENCES `a-king-s-ransom`.`providers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp1251;

USE `a-king-s-ransom` ;

-- -----------------------------------------------------
-- procedure Create_product_in_stock
-- -----------------------------------------------------

DELIMITER $$
USE `a-king-s-ransom`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `Create_product_in_stock`()
BEGIN
 
INSERT `a-king-s-ransom`.products (name , quantity , unit_price)
VALUES ('pr',3,3.4);
INSERT `a-king-s-ransom`.product_in_stock (product_in_stock_ID ,provider_ID,receipt_date)
VALUES (last_insert_id(),5,"2010-10-10");
COMMIT;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
