package com.loneliness.server.controller;

public enum  CommandName {
     WRONG_REQUEST, AUTHORIZATION_USER, CREATE_USER, DELETE_USER, RECEIVE_USER, RECEIVE_ALL_USERS, UPDATE_USER, SHUT_DOWN,
     FIND_USERS_BY_LOGIN_AND_TYPE, RECEIVE_ALL_USERS_IN_LIMIT
}
