package com.loneliness.client.controller;

 enum  CommandName {
     WRONG_REQUEST,

     CREATE_USER, AUTHORIZE, DELETE_USER, RECEIVE_ALL_USERS, RECEIVE_USER_DATA, UPDATE_USER,
     FIND_USERS_BY_LOGIN_AND_TYPE,RECEIVE_ALL_USERS_IN_LIMIT, USER_DATA_VALIDATION, USER_PRIVATE_DATA_VALIDATION,

     RECEIVE_ALL_PROVIDERS_IN_LIMIT, CREATE_PROVIDER, DELETE_PROVIDER, RECEIVE_ALL_PROVIDERS, RECEIVE_PROVIDER_DATA,
     UPDATE_PROVIDER, FIND_PROVIDER_BY_LOCATION_AND_RATING,
     PROVIDER_VALIDATION,

     CREATE_ORDER, DELETE_ORDER, FIND_ALL_ORDERS_BY_DATE_OF_COMPLETION_AND_STATUS, RECEIVE_ALL_ORDERS,
     RECEIVE_ALL_ORDERS_IN_LIMIT, RECEIVE_ORDER_DATA, UPDATE_ORDER, ORDER_DATA_VALIDATION,

     CUSTOMER_DATA_VALIDATION
}
