package com.loneliness.client.controller;

 enum  CommandName {
     WRONG_REQUEST, CREATE_USER, AUTHORIZE, DELETE_USER, RECEIVE_ALL_USERS, RECEIVE_USER_DATA, UPDATE_USER,
     FIND_USERS_BY_LOGIN_AND_TYPE,RECEIVE_ALL_USERS_IN_LIMIT
}
